/*
 * 轻应用Baas平台API
 * demo
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.chinamobile.iot.baas.sdk;

import sun.misc.BASE64Encoder;

import javax.crypto.Mac;
import javax.crypto.SecretKey;
import javax.crypto.spec.SecretKeySpec;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-26T17:00:09.998+08:00")
public class HMACSHA1Util {

    public final static String HMAC_SHA1 = "HmacSHA1";

       public static String HmacSHA1Encode(String encodeRules,String content) throws Exception{
           try {
               byte[] keyBytes = encodeRules.getBytes("utf-8");

               SecretKey secretKey = new SecretKeySpec(keyBytes, HMAC_SHA1);

               Mac mac = Mac.getInstance(HMAC_SHA1);

               mac.init(secretKey);

               byte[] rawHmac = mac.doFinal(content.getBytes("utf-8"));

               String HmacSHA1_encode = new String(new BASE64Encoder().encode(rawHmac));

               return HmacSHA1_encode;
           }catch (Exception e){
               e.printStackTrace();
           }
           return null;
       }

}
