/*
 * 轻应用Baas平台API
 * demo
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.chinamobile.iot.baas.sdk.api;

import com.chinamobile.iot.baas.sdk.ApiException;
import com.chinamobile.iot.baas.sdk.model.RoleNameListResponse;
import org.junit.Ignore;
import org.junit.Assert;
import org.junit.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.junit.Before;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RoleApi
 */
@Ignore
public class RoleApiTest {

    private String accessId = "";
    private String accessKey = "";
    private static Logger logger = LoggerFactory.getLogger(RoleApiTest.class);
    private String sessionToken;
    private String appToken = "";
    private String basePath = "http://demo.heclouds.com/baasapi";

    private final RoleApi api = new RoleApi(basePath,accessId,accessKey);

      @Before
        public void getSessionToken(){
            AuthApi authApi = new AuthApi(basePath,accessId,accessKey);
            String loginName = "";
            String password = "";
            try {
                sessionToken = authApi.loginPostSessionToken(appToken, loginName, password);
                logger.info("获取sessionToken成功,session-token： "+sessionToken);
            }catch (Exception e){
                logger.error("获取sessionToken失败： "+e.getMessage());
            }
        }

    
    /**
     * 查询允许注册的角色
     *
     * 查询允许注册的角色
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findRoleAllowRegUsingGETTest() throws ApiException {
        String appToken = null;
        List<RoleNameListResponse> response = api.findRoleAllowRegUsingGET(appToken);

        // TODO: test validations
    }
    
    /**
     * 查询当前用户所能创建的角色
     *
     * 查询当前用户所能创建的角色
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findRoleNameListUsingGETTest() throws ApiException {
        List<RoleNameListResponse> response = api.findRoleNameListUsingGET(sessionToken);

        // TODO: test validations
    }
    
}
