/*
 * 轻应用Baas平台API
 * demo
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.chinamobile.iot.baas.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.Date;

/**
 * CommandStatus
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-26T17:00:09.998+08:00")
public class CommandStatus {
  @SerializedName("cmdUuid")
  private String cmdUuid = null;

  @SerializedName("commandContent")
  private String commandContent = null;

  @SerializedName("commandId")
  private Long commandId = null;

  @SerializedName("commandName")
  private String commandName = null;

  @SerializedName("createDate")
  private Date createDate = null;

  @SerializedName("deviceId")
  private String deviceId = null;

  @SerializedName("status")
  private Integer status = null;

  public CommandStatus cmdUuid(String cmdUuid) {
    this.cmdUuid = cmdUuid;
    return this;
  }

   /**
   * Get cmdUuid
   * @return cmdUuid
  **/
  @ApiModelProperty(value = "")
  public String getCmdUuid() {
    return cmdUuid;
  }

  public void setCmdUuid(String cmdUuid) {
    this.cmdUuid = cmdUuid;
  }

  public CommandStatus commandContent(String commandContent) {
    this.commandContent = commandContent;
    return this;
  }

   /**
   * Get commandContent
   * @return commandContent
  **/
  @ApiModelProperty(value = "")
  public String getCommandContent() {
    return commandContent;
  }

  public void setCommandContent(String commandContent) {
    this.commandContent = commandContent;
  }

  public CommandStatus commandId(Long commandId) {
    this.commandId = commandId;
    return this;
  }

   /**
   * Get commandId
   * @return commandId
  **/
  @ApiModelProperty(value = "")
  public Long getCommandId() {
    return commandId;
  }

  public void setCommandId(Long commandId) {
    this.commandId = commandId;
  }

  public CommandStatus commandName(String commandName) {
    this.commandName = commandName;
    return this;
  }

   /**
   * Get commandName
   * @return commandName
  **/
  @ApiModelProperty(value = "")
  public String getCommandName() {
    return commandName;
  }

  public void setCommandName(String commandName) {
    this.commandName = commandName;
  }

  public CommandStatus createDate(Date createDate) {
    this.createDate = createDate;
    return this;
  }

   /**
   * Get createDate
   * @return createDate
  **/
  @ApiModelProperty(value = "")
  public Date getCreateDate() {
    return createDate;
  }

  public void setCreateDate(Date createDate) {
    this.createDate = createDate;
  }

  public CommandStatus deviceId(String deviceId) {
    this.deviceId = deviceId;
    return this;
  }

   /**
   * Get deviceId
   * @return deviceId
  **/
  @ApiModelProperty(value = "")
  public String getDeviceId() {
    return deviceId;
  }

  public void setDeviceId(String deviceId) {
    this.deviceId = deviceId;
  }

  public CommandStatus status(Integer status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public Integer getStatus() {
    return status;
  }

  public void setStatus(Integer status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CommandStatus commandStatus = (CommandStatus) o;
    return Objects.equals(this.cmdUuid, commandStatus.cmdUuid) &&
        Objects.equals(this.commandContent, commandStatus.commandContent) &&
        Objects.equals(this.commandId, commandStatus.commandId) &&
        Objects.equals(this.commandName, commandStatus.commandName) &&
        Objects.equals(this.createDate, commandStatus.createDate) &&
        Objects.equals(this.deviceId, commandStatus.deviceId) &&
        Objects.equals(this.status, commandStatus.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cmdUuid, commandContent, commandId, commandName, createDate, deviceId, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CommandStatus {\n");
    
    sb.append("    cmdUuid: ").append(toIndentedString(cmdUuid)).append("\n");
    sb.append("    commandContent: ").append(toIndentedString(commandContent)).append("\n");
    sb.append("    commandId: ").append(toIndentedString(commandId)).append("\n");
    sb.append("    commandName: ").append(toIndentedString(commandName)).append("\n");
    sb.append("    createDate: ").append(toIndentedString(createDate)).append("\n");
    sb.append("    deviceId: ").append(toIndentedString(deviceId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

