/*
 * 轻应用Baas平台API
 * demo
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.chinamobile.iot.baas.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * 发送命令响应
 */
@ApiModel(description = "发送命令响应")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-26T17:00:09.998+08:00")
public class CommandResult {
  @SerializedName("cmdUuid")
  private String cmdUuid = null;

  public CommandResult cmdUuid(String cmdUuid) {
    this.cmdUuid = cmdUuid;
    return this;
  }

   /**
   * 命令唯一标识码
   * @return cmdUuid
  **/
  @ApiModelProperty(value = "命令唯一标识码")
  public String getCmdUuid() {
    return cmdUuid;
  }

  public void setCmdUuid(String cmdUuid) {
    this.cmdUuid = cmdUuid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CommandResult commandResult = (CommandResult) o;
    return Objects.equals(this.cmdUuid, commandResult.cmdUuid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cmdUuid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CommandResult {\n");
    
    sb.append("    cmdUuid: ").append(toIndentedString(cmdUuid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

