/*
 * 轻应用Baas平台API
 * demo
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.chinamobile.iot.baas.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * 添加转授响应
 */
@ApiModel(description = "添加转授响应")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-26T17:00:09.998+08:00")
public class DelegateIdResponse {
  @SerializedName("delegateId")
  private Integer delegateId = null;

  public DelegateIdResponse delegateId(Integer delegateId) {
    this.delegateId = delegateId;
    return this;
  }

   /**
   * 转授Id
   * @return delegateId
  **/
  @ApiModelProperty(value = "转授Id")
  public Integer getDelegateId() {
    return delegateId;
  }

  public void setDelegateId(Integer delegateId) {
    this.delegateId = delegateId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DelegateIdResponse delegateIdResponse = (DelegateIdResponse) o;
    return Objects.equals(this.delegateId, delegateIdResponse.delegateId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(delegateId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DelegateIdResponse {\n");
    
    sb.append("    delegateId: ").append(toIndentedString(delegateId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

