/*
 * 轻应用Baas平台API
 * demo
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.chinamobile.iot.baas.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.chinamobile.iot.baas.sdk.model.AddDevice;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * 批量导入设备请求
 */
@ApiModel(description = "批量导入设备请求")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-26T17:00:09.998+08:00")
public class DeviceImport {
  @SerializedName("devices")
  private List<AddDevice> devices = null;

  public DeviceImport devices(List<AddDevice> devices) {
    this.devices = devices;
    return this;
  }

  public DeviceImport addDevicesItem(AddDevice devicesItem) {
    if (this.devices == null) {
      this.devices = new ArrayList<AddDevice>();
    }
    this.devices.add(devicesItem);
    return this;
  }

   /**
   * 批量导入的设备信息列表
   * @return devices
  **/
  @ApiModelProperty(value = "批量导入的设备信息列表")
  public List<AddDevice> getDevices() {
    return devices;
  }

  public void setDevices(List<AddDevice> devices) {
    this.devices = devices;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeviceImport deviceImport = (DeviceImport) o;
    return Objects.equals(this.devices, deviceImport.devices);
  }

  @Override
  public int hashCode() {
    return Objects.hash(devices);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeviceImport {\n");
    
    sb.append("    devices: ").append(toIndentedString(devices)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

