/*
 * 轻应用Baas平台API
 * demo
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.chinamobile.iot.baas.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.Date;

/**
 * 设备转授信息查询响应
 */
@ApiModel(description = "设备转授信息查询响应")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-26T17:00:09.998+08:00")
public class DeviceDelegationsResponse {
  @SerializedName("delegateDate")
  private Date delegateDate = null;

  @SerializedName("delegateId")
  private Integer delegateId = null;

  @SerializedName("delegateLevel")
  private Integer delegateLevel = null;

  @SerializedName("deviceId")
  private String deviceId = null;

  @SerializedName("fromUserLoginName")
  private String fromUserLoginName = null;

  @SerializedName("toUserLoginName")
  private String toUserLoginName = null;

  public DeviceDelegationsResponse delegateDate(Date delegateDate) {
    this.delegateDate = delegateDate;
    return this;
  }

   /**
   * 转授日期
   * @return delegateDate
  **/
  @ApiModelProperty(value = "转授日期")
  public Date getDelegateDate() {
    return delegateDate;
  }

  public void setDelegateDate(Date delegateDate) {
    this.delegateDate = delegateDate;
  }

  public DeviceDelegationsResponse delegateId(Integer delegateId) {
    this.delegateId = delegateId;
    return this;
  }

   /**
   * 转授Id
   * @return delegateId
  **/
  @ApiModelProperty(value = "转授Id")
  public Integer getDelegateId() {
    return delegateId;
  }

  public void setDelegateId(Integer delegateId) {
    this.delegateId = delegateId;
  }

  public DeviceDelegationsResponse delegateLevel(Integer delegateLevel) {
    this.delegateLevel = delegateLevel;
    return this;
  }

   /**
   * 转授等级
   * @return delegateLevel
  **/
  @ApiModelProperty(value = "转授等级")
  public Integer getDelegateLevel() {
    return delegateLevel;
  }

  public void setDelegateLevel(Integer delegateLevel) {
    this.delegateLevel = delegateLevel;
  }

  public DeviceDelegationsResponse deviceId(String deviceId) {
    this.deviceId = deviceId;
    return this;
  }

   /**
   * 设备Id
   * @return deviceId
  **/
  @ApiModelProperty(value = "设备Id")
  public String getDeviceId() {
    return deviceId;
  }

  public void setDeviceId(String deviceId) {
    this.deviceId = deviceId;
  }

  public DeviceDelegationsResponse fromUserLoginName(String fromUserLoginName) {
    this.fromUserLoginName = fromUserLoginName;
    return this;
  }

   /**
   * 设备转授人
   * @return fromUserLoginName
  **/
  @ApiModelProperty(value = "设备转授人")
  public String getFromUserLoginName() {
    return fromUserLoginName;
  }

  public void setFromUserLoginName(String fromUserLoginName) {
    this.fromUserLoginName = fromUserLoginName;
  }

  public DeviceDelegationsResponse toUserLoginName(String toUserLoginName) {
    this.toUserLoginName = toUserLoginName;
    return this;
  }

   /**
   * 转授给的用户
   * @return toUserLoginName
  **/
  @ApiModelProperty(value = "转授给的用户")
  public String getToUserLoginName() {
    return toUserLoginName;
  }

  public void setToUserLoginName(String toUserLoginName) {
    this.toUserLoginName = toUserLoginName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeviceDelegationsResponse deviceDelegationsResponse = (DeviceDelegationsResponse) o;
    return Objects.equals(this.delegateDate, deviceDelegationsResponse.delegateDate) &&
        Objects.equals(this.delegateId, deviceDelegationsResponse.delegateId) &&
        Objects.equals(this.delegateLevel, deviceDelegationsResponse.delegateLevel) &&
        Objects.equals(this.deviceId, deviceDelegationsResponse.deviceId) &&
        Objects.equals(this.fromUserLoginName, deviceDelegationsResponse.fromUserLoginName) &&
        Objects.equals(this.toUserLoginName, deviceDelegationsResponse.toUserLoginName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(delegateDate, delegateId, delegateLevel, deviceId, fromUserLoginName, toUserLoginName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeviceDelegationsResponse {\n");
    
    sb.append("    delegateDate: ").append(toIndentedString(delegateDate)).append("\n");
    sb.append("    delegateId: ").append(toIndentedString(delegateId)).append("\n");
    sb.append("    delegateLevel: ").append(toIndentedString(delegateLevel)).append("\n");
    sb.append("    deviceId: ").append(toIndentedString(deviceId)).append("\n");
    sb.append("    fromUserLoginName: ").append(toIndentedString(fromUserLoginName)).append("\n");
    sb.append("    toUserLoginName: ").append(toIndentedString(toUserLoginName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

