/*
 * 轻应用Baas平台API
 * demo
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.chinamobile.iot.baas.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.chinamobile.iot.baas.sdk.model.FailedDevices;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * 批量导入设备响应
 */
@ApiModel(description = "批量导入设备响应")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-26T17:00:09.998+08:00")
public class DeviceImportResponse {
  @SerializedName("failedCount")
  private Integer failedCount = null;

  @SerializedName("failedDevices")
  private List<FailedDevices> failedDevices = null;

  @SerializedName("successCount")
  private Integer successCount = null;

  public DeviceImportResponse failedCount(Integer failedCount) {
    this.failedCount = failedCount;
    return this;
  }

   /**
   * 导入失败的条数
   * @return failedCount
  **/
  @ApiModelProperty(value = "导入失败的条数")
  public Integer getFailedCount() {
    return failedCount;
  }

  public void setFailedCount(Integer failedCount) {
    this.failedCount = failedCount;
  }

  public DeviceImportResponse failedDevices(List<FailedDevices> failedDevices) {
    this.failedDevices = failedDevices;
    return this;
  }

  public DeviceImportResponse addFailedDevicesItem(FailedDevices failedDevicesItem) {
    if (this.failedDevices == null) {
      this.failedDevices = new ArrayList<FailedDevices>();
    }
    this.failedDevices.add(failedDevicesItem);
    return this;
  }

   /**
   * 导入失败的具体信息
   * @return failedDevices
  **/
  @ApiModelProperty(value = "导入失败的具体信息")
  public List<FailedDevices> getFailedDevices() {
    return failedDevices;
  }

  public void setFailedDevices(List<FailedDevices> failedDevices) {
    this.failedDevices = failedDevices;
  }

  public DeviceImportResponse successCount(Integer successCount) {
    this.successCount = successCount;
    return this;
  }

   /**
   * 导入成功的条数
   * @return successCount
  **/
  @ApiModelProperty(value = "导入成功的条数")
  public Integer getSuccessCount() {
    return successCount;
  }

  public void setSuccessCount(Integer successCount) {
    this.successCount = successCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeviceImportResponse deviceImportResponse = (DeviceImportResponse) o;
    return Objects.equals(this.failedCount, deviceImportResponse.failedCount) &&
        Objects.equals(this.failedDevices, deviceImportResponse.failedDevices) &&
        Objects.equals(this.successCount, deviceImportResponse.successCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(failedCount, failedDevices, successCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeviceImportResponse {\n");
    
    sb.append("    failedCount: ").append(toIndentedString(failedCount)).append("\n");
    sb.append("    failedDevices: ").append(toIndentedString(failedDevices)).append("\n");
    sb.append("    successCount: ").append(toIndentedString(successCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

