/*
 * 轻应用Baas平台API
 * demo
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.chinamobile.iot.baas.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.Date;

/**
 * DeviceSharesDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-26T17:00:09.998+08:00")
public class DeviceSharesDTO {
  @SerializedName("deviceId")
  private String deviceId = null;

  @SerializedName("fromUserLoginName")
  private String fromUserLoginName = null;

  @SerializedName("fromUserUserName")
  private String fromUserUserName = null;

  @SerializedName("permissions")
  private String permissions = null;

  @SerializedName("shareDate")
  private Date shareDate = null;

  @SerializedName("shareId")
  private Integer shareId = null;

  @SerializedName("toUserLoginName")
  private String toUserLoginName = null;

  @SerializedName("toUserUserName")
  private String toUserUserName = null;

  public DeviceSharesDTO deviceId(String deviceId) {
    this.deviceId = deviceId;
    return this;
  }

   /**
   * Get deviceId
   * @return deviceId
  **/
  @ApiModelProperty(value = "")
  public String getDeviceId() {
    return deviceId;
  }

  public void setDeviceId(String deviceId) {
    this.deviceId = deviceId;
  }

  public DeviceSharesDTO fromUserLoginName(String fromUserLoginName) {
    this.fromUserLoginName = fromUserLoginName;
    return this;
  }

   /**
   * Get fromUserLoginName
   * @return fromUserLoginName
  **/
  @ApiModelProperty(value = "")
  public String getFromUserLoginName() {
    return fromUserLoginName;
  }

  public void setFromUserLoginName(String fromUserLoginName) {
    this.fromUserLoginName = fromUserLoginName;
  }

  public DeviceSharesDTO fromUserUserName(String fromUserUserName) {
    this.fromUserUserName = fromUserUserName;
    return this;
  }

   /**
   * Get fromUserUserName
   * @return fromUserUserName
  **/
  @ApiModelProperty(value = "")
  public String getFromUserUserName() {
    return fromUserUserName;
  }

  public void setFromUserUserName(String fromUserUserName) {
    this.fromUserUserName = fromUserUserName;
  }

  public DeviceSharesDTO permissions(String permissions) {
    this.permissions = permissions;
    return this;
  }

   /**
   * Get permissions
   * @return permissions
  **/
  @ApiModelProperty(value = "")
  public String getPermissions() {
    return permissions;
  }

  public void setPermissions(String permissions) {
    this.permissions = permissions;
  }

  public DeviceSharesDTO shareDate(Date shareDate) {
    this.shareDate = shareDate;
    return this;
  }

   /**
   * Get shareDate
   * @return shareDate
  **/
  @ApiModelProperty(value = "")
  public Date getShareDate() {
    return shareDate;
  }

  public void setShareDate(Date shareDate) {
    this.shareDate = shareDate;
  }

  public DeviceSharesDTO shareId(Integer shareId) {
    this.shareId = shareId;
    return this;
  }

   /**
   * Get shareId
   * @return shareId
  **/
  @ApiModelProperty(value = "")
  public Integer getShareId() {
    return shareId;
  }

  public void setShareId(Integer shareId) {
    this.shareId = shareId;
  }

  public DeviceSharesDTO toUserLoginName(String toUserLoginName) {
    this.toUserLoginName = toUserLoginName;
    return this;
  }

   /**
   * Get toUserLoginName
   * @return toUserLoginName
  **/
  @ApiModelProperty(value = "")
  public String getToUserLoginName() {
    return toUserLoginName;
  }

  public void setToUserLoginName(String toUserLoginName) {
    this.toUserLoginName = toUserLoginName;
  }

  public DeviceSharesDTO toUserUserName(String toUserUserName) {
    this.toUserUserName = toUserUserName;
    return this;
  }

   /**
   * Get toUserUserName
   * @return toUserUserName
  **/
  @ApiModelProperty(value = "")
  public String getToUserUserName() {
    return toUserUserName;
  }

  public void setToUserUserName(String toUserUserName) {
    this.toUserUserName = toUserUserName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeviceSharesDTO deviceSharesDTO = (DeviceSharesDTO) o;
    return Objects.equals(this.deviceId, deviceSharesDTO.deviceId) &&
        Objects.equals(this.fromUserLoginName, deviceSharesDTO.fromUserLoginName) &&
        Objects.equals(this.fromUserUserName, deviceSharesDTO.fromUserUserName) &&
        Objects.equals(this.permissions, deviceSharesDTO.permissions) &&
        Objects.equals(this.shareDate, deviceSharesDTO.shareDate) &&
        Objects.equals(this.shareId, deviceSharesDTO.shareId) &&
        Objects.equals(this.toUserLoginName, deviceSharesDTO.toUserLoginName) &&
        Objects.equals(this.toUserUserName, deviceSharesDTO.toUserUserName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deviceId, fromUserLoginName, fromUserUserName, permissions, shareDate, shareId, toUserLoginName, toUserUserName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeviceSharesDTO {\n");
    
    sb.append("    deviceId: ").append(toIndentedString(deviceId)).append("\n");
    sb.append("    fromUserLoginName: ").append(toIndentedString(fromUserLoginName)).append("\n");
    sb.append("    fromUserUserName: ").append(toIndentedString(fromUserUserName)).append("\n");
    sb.append("    permissions: ").append(toIndentedString(permissions)).append("\n");
    sb.append("    shareDate: ").append(toIndentedString(shareDate)).append("\n");
    sb.append("    shareId: ").append(toIndentedString(shareId)).append("\n");
    sb.append("    toUserLoginName: ").append(toIndentedString(toUserLoginName)).append("\n");
    sb.append("    toUserUserName: ").append(toIndentedString(toUserUserName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

