/*
 * 轻应用Baas平台API
 * demo
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.chinamobile.iot.baas.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * FindMongoDataRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-26T17:00:09.998+08:00")
public class FindMongoDataRequest {
  @SerializedName("limit")
  private Integer limit = null;

  @SerializedName("params")
  private Object params = null;

  @SerializedName("sqlTemplateId")
  private Integer sqlTemplateId = null;

  @SerializedName("tableName")
  private String tableName = null;

  public FindMongoDataRequest limit(Integer limit) {
    this.limit = limit;
    return this;
  }

   /**
   * 数量限制
   * @return limit
  **/
  @ApiModelProperty(value = "数量限制")
  public Integer getLimit() {
    return limit;
  }

  public void setLimit(Integer limit) {
    this.limit = limit;
  }

  public FindMongoDataRequest params(Object params) {
    this.params = params;
    return this;
  }

   /**
   * 模板参数
   * @return params
  **/
  @ApiModelProperty(value = "模板参数")
  public Object getParams() {
    return params;
  }

  public void setParams(Object params) {
    this.params = params;
  }

  public FindMongoDataRequest sqlTemplateId(Integer sqlTemplateId) {
    this.sqlTemplateId = sqlTemplateId;
    return this;
  }

   /**
   * sql模板Id
   * @return sqlTemplateId
  **/
  @ApiModelProperty(value = "sql模板Id")
  public Integer getSqlTemplateId() {
    return sqlTemplateId;
  }

  public void setSqlTemplateId(Integer sqlTemplateId) {
    this.sqlTemplateId = sqlTemplateId;
  }

  public FindMongoDataRequest tableName(String tableName) {
    this.tableName = tableName;
    return this;
  }

   /**
   * 目标表名
   * @return tableName
  **/
  @ApiModelProperty(value = "目标表名")
  public String getTableName() {
    return tableName;
  }

  public void setTableName(String tableName) {
    this.tableName = tableName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FindMongoDataRequest findMongoDataRequest = (FindMongoDataRequest) o;
    return Objects.equals(this.limit, findMongoDataRequest.limit) &&
        Objects.equals(this.params, findMongoDataRequest.params) &&
        Objects.equals(this.sqlTemplateId, findMongoDataRequest.sqlTemplateId) &&
        Objects.equals(this.tableName, findMongoDataRequest.tableName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(limit, params, sqlTemplateId, tableName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FindMongoDataRequest {\n");
    
    sb.append("    limit: ").append(toIndentedString(limit)).append("\n");
    sb.append("    params: ").append(toIndentedString(params)).append("\n");
    sb.append("    sqlTemplateId: ").append(toIndentedString(sqlTemplateId)).append("\n");
    sb.append("    tableName: ").append(toIndentedString(tableName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

