/*
 * 轻应用Baas平台API
 * demo
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.chinamobile.iot.baas.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * MongoDataWithDeviceIdRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-26T17:00:09.998+08:00")
public class MongoDataWithDeviceIdRequest {
  @SerializedName("deviceIds")
  private List<String> deviceIds = null;

  @SerializedName("params")
  private Object params = null;

  @SerializedName("sqlTemplateId")
  private Integer sqlTemplateId = null;

  @SerializedName("tableName")
  private String tableName = null;

  public MongoDataWithDeviceIdRequest deviceIds(List<String> deviceIds) {
    this.deviceIds = deviceIds;
    return this;
  }

  public MongoDataWithDeviceIdRequest addDeviceIdsItem(String deviceIdsItem) {
    if (this.deviceIds == null) {
      this.deviceIds = new ArrayList<String>();
    }
    this.deviceIds.add(deviceIdsItem);
    return this;
  }

   /**
   * 设备Id列表限制
   * @return deviceIds
  **/
  @ApiModelProperty(value = "设备Id列表限制")
  public List<String> getDeviceIds() {
    return deviceIds;
  }

  public void setDeviceIds(List<String> deviceIds) {
    this.deviceIds = deviceIds;
  }

  public MongoDataWithDeviceIdRequest params(Object params) {
    this.params = params;
    return this;
  }

   /**
   * 模板参数
   * @return params
  **/
  @ApiModelProperty(value = "模板参数")
  public Object getParams() {
    return params;
  }

  public void setParams(Object params) {
    this.params = params;
  }

  public MongoDataWithDeviceIdRequest sqlTemplateId(Integer sqlTemplateId) {
    this.sqlTemplateId = sqlTemplateId;
    return this;
  }

   /**
   * sql模板Id
   * @return sqlTemplateId
  **/
  @ApiModelProperty(value = "sql模板Id")
  public Integer getSqlTemplateId() {
    return sqlTemplateId;
  }

  public void setSqlTemplateId(Integer sqlTemplateId) {
    this.sqlTemplateId = sqlTemplateId;
  }

  public MongoDataWithDeviceIdRequest tableName(String tableName) {
    this.tableName = tableName;
    return this;
  }

   /**
   * 目标表名
   * @return tableName
  **/
  @ApiModelProperty(value = "目标表名")
  public String getTableName() {
    return tableName;
  }

  public void setTableName(String tableName) {
    this.tableName = tableName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MongoDataWithDeviceIdRequest mongoDataWithDeviceIdRequest = (MongoDataWithDeviceIdRequest) o;
    return Objects.equals(this.deviceIds, mongoDataWithDeviceIdRequest.deviceIds) &&
        Objects.equals(this.params, mongoDataWithDeviceIdRequest.params) &&
        Objects.equals(this.sqlTemplateId, mongoDataWithDeviceIdRequest.sqlTemplateId) &&
        Objects.equals(this.tableName, mongoDataWithDeviceIdRequest.tableName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deviceIds, params, sqlTemplateId, tableName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MongoDataWithDeviceIdRequest {\n");
    
    sb.append("    deviceIds: ").append(toIndentedString(deviceIds)).append("\n");
    sb.append("    params: ").append(toIndentedString(params)).append("\n");
    sb.append("    sqlTemplateId: ").append(toIndentedString(sqlTemplateId)).append("\n");
    sb.append("    tableName: ").append(toIndentedString(tableName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

