/*
 * 轻应用Baas平台API
 * demo
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.chinamobile.iot.baas.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * 发送命令请求
 */
@ApiModel(description = "发送命令请求")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-26T17:00:09.998+08:00")
public class SendCommandRequest {
  @SerializedName("commandName")
  private String commandName = null;

  @SerializedName("commandVar")
  private Object commandVar = null;

  @SerializedName("deviceId")
  private String deviceId = null;

  public SendCommandRequest commandName(String commandName) {
    this.commandName = commandName;
    return this;
  }

   /**
   * 命令名
   * @return commandName
  **/
  @ApiModelProperty(value = "命令名")
  public String getCommandName() {
    return commandName;
  }

  public void setCommandName(String commandName) {
    this.commandName = commandName;
  }

  public SendCommandRequest commandVar(Object commandVar) {
    this.commandVar = commandVar;
    return this;
  }

   /**
   * 命令参数
   * @return commandVar
  **/
  @ApiModelProperty(value = "命令参数")
  public Object getCommandVar() {
    return commandVar;
  }

  public void setCommandVar(Object commandVar) {
    this.commandVar = commandVar;
  }

  public SendCommandRequest deviceId(String deviceId) {
    this.deviceId = deviceId;
    return this;
  }

   /**
   * 设备Id
   * @return deviceId
  **/
  @ApiModelProperty(value = "设备Id")
  public String getDeviceId() {
    return deviceId;
  }

  public void setDeviceId(String deviceId) {
    this.deviceId = deviceId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SendCommandRequest sendCommandRequest = (SendCommandRequest) o;
    return Objects.equals(this.commandName, sendCommandRequest.commandName) &&
        Objects.equals(this.commandVar, sendCommandRequest.commandVar) &&
        Objects.equals(this.deviceId, sendCommandRequest.deviceId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(commandName, commandVar, deviceId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SendCommandRequest {\n");
    
    sb.append("    commandName: ").append(toIndentedString(commandName)).append("\n");
    sb.append("    commandVar: ").append(toIndentedString(commandVar)).append("\n");
    sb.append("    deviceId: ").append(toIndentedString(deviceId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

