/*
 * 轻应用Baas平台API
 * demo
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.chinamobile.iot.baas.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * 修改设备档案请求
 */
@ApiModel(description = "修改设备档案请求")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-26T17:00:09.998+08:00")
public class UpdateArchive {
  @SerializedName("archiveName")
  private String archiveName = null;

  @SerializedName("data")
  private Object data = null;

  @SerializedName("recordId")
  private String recordId = null;

  public UpdateArchive archiveName(String archiveName) {
    this.archiveName = archiveName;
    return this;
  }

   /**
   * 档案类型
   * @return archiveName
  **/
  @ApiModelProperty(value = "档案类型")
  public String getArchiveName() {
    return archiveName;
  }

  public void setArchiveName(String archiveName) {
    this.archiveName = archiveName;
  }

  public UpdateArchive data(Object data) {
    this.data = data;
    return this;
  }

   /**
   * 档案数据
   * @return data
  **/
  @ApiModelProperty(value = "档案数据")
  public Object getData() {
    return data;
  }

  public void setData(Object data) {
    this.data = data;
  }

  public UpdateArchive recordId(String recordId) {
    this.recordId = recordId;
    return this;
  }

   /**
   * 档案ID
   * @return recordId
  **/
  @ApiModelProperty(value = "档案ID")
  public String getRecordId() {
    return recordId;
  }

  public void setRecordId(String recordId) {
    this.recordId = recordId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateArchive updateArchive = (UpdateArchive) o;
    return Objects.equals(this.archiveName, updateArchive.archiveName) &&
        Objects.equals(this.data, updateArchive.data) &&
        Objects.equals(this.recordId, updateArchive.recordId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(archiveName, data, recordId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateArchive {\n");
    
    sb.append("    archiveName: ").append(toIndentedString(archiveName)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    recordId: ").append(toIndentedString(recordId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

