/*
 * 轻应用Baas平台API
 * demo
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.chinamobile.iot.baas.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * 修改设备信息请求
 */
@ApiModel(description = "修改设备信息请求")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-26T17:00:09.998+08:00")
public class UpdateDevice {
  @SerializedName("deviceGroupId")
  private Integer deviceGroupId = null;

  @SerializedName("deviceName")
  private String deviceName = null;

  @SerializedName("extension")
  private Object extension = null;

  public UpdateDevice deviceGroupId(Integer deviceGroupId) {
    this.deviceGroupId = deviceGroupId;
    return this;
  }

   /**
   * 设备分组ID
   * @return deviceGroupId
  **/
  @ApiModelProperty(value = "设备分组ID")
  public Integer getDeviceGroupId() {
    return deviceGroupId;
  }

  public void setDeviceGroupId(Integer deviceGroupId) {
    this.deviceGroupId = deviceGroupId;
  }

  public UpdateDevice deviceName(String deviceName) {
    this.deviceName = deviceName;
    return this;
  }

   /**
   * 设备名
   * @return deviceName
  **/
  @ApiModelProperty(value = "设备名")
  public String getDeviceName() {
    return deviceName;
  }

  public void setDeviceName(String deviceName) {
    this.deviceName = deviceName;
  }

  public UpdateDevice extension(Object extension) {
    this.extension = extension;
    return this;
  }

   /**
   * 设备扩展信息
   * @return extension
  **/
  @ApiModelProperty(value = "设备扩展信息")
  public Object getExtension() {
    return extension;
  }

  public void setExtension(Object extension) {
    this.extension = extension;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateDevice updateDevice = (UpdateDevice) o;
    return Objects.equals(this.deviceGroupId, updateDevice.deviceGroupId) &&
        Objects.equals(this.deviceName, updateDevice.deviceName) &&
        Objects.equals(this.extension, updateDevice.extension);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deviceGroupId, deviceName, extension);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateDevice {\n");
    
    sb.append("    deviceGroupId: ").append(toIndentedString(deviceGroupId)).append("\n");
    sb.append("    deviceName: ").append(toIndentedString(deviceName)).append("\n");
    sb.append("    extension: ").append(toIndentedString(extension)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

